_ISIN_COUNTRY: dict[str, str] = {
    "AT": "Austria",
    "AU": "Australia",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "BR": "Brazil",
    "CA": "Canada",
    "CH": "Switzerland",
    "CN": "China",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DK": "Denmark",
    "EE": "Estonia",
    "ES": "Spain",
    "FI": "Finland",
    "FR": "France",
    "GB": "United Kingdom",
    "GG": "Guernsey",
    "GR": "Greece",
    "HK": "Hong Kong",
    "HR": "Croatia",
    "HU": "Hungary",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JP": "Japan",
    "KY": "Cayman Islands",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "MT": "Malta",
    "MU": "Mauritius",
    "NL": "Netherlands",
    "NO": "Norway",
    "NZ": "New Zealand",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SE": "Sweden",
    "SG": "Singapore",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "US": "United States",
    "VG": "British Virgin Islands",
    "XS": "Eurobond (International)",
}


def isin_to_country(isin: str | None) -> str | None:
    if not isin or len(isin) < 2:
        return None
    return _ISIN_COUNTRY.get(isin[:2].upper())
